### ISSUE TITLE
error: "Request failed with status code 401" 

### ISSUE THREAD

**Issue by GPorter43** [imranhsayed/nextjs-woocommerce-restapi#13]
When using the NextJS Url in the general settings i get a 401 error if i use the wordpress site settings i get products back, unfortunately the permalinks are referencing the wordpress site. Is there a way to pass CORS headers in the get request?

**Comment by imranhsayed** [comment]
@GPorter43 
- Thanks for bringing this up 👍 
- Passing CORS header is not required.
-  When we set site address url to frontend url, by default wp rest endpoint gets that frontend url as base point.
-  So an actual backend url required an update for REST api only. I have made the changes to the Headlesss CMS Plugin

`So this is resolved`, Please `pull the latest changes` from https://github.com/imranhsayed/headless-cms or download the latest version of the plugin.

**Comment by GPorter43** [comment]
Brilliant that works perfectly
