### ISSUE TITLE
404 error, wp json doesnt load

### ISSUE THREAD

**Issue by ello-lithuania** [imranhsayed/nextjs-woocommerce-restapi#15]
![image](https://user-images.githubusercontent.com/63595651/138603321-112b94af-6359-4535-b32b-fa7a14db3cea.png)
![image](https://user-images.githubusercontent.com/63595651/138603334-a893000e-834e-41c7-bb0b-8e78e67e9ed4.png)
![image](https://user-images.githubusercontent.com/63595651/138603345-3d6a6350-bd16-44f8-951a-a4f88fead454.png)

**Comment by nagolicitest** [comment]
Have opened an issue - mine is of a similar nature. When updating the SITE URL on the WordPress dashboard and refreshing the returned JSON data. The page refreshed the URL to match the SITE URL i have just changed and returns a 404. A little confused as to why it is doing this as not mirrored in the tutorial? im thinking its to do with the config in HCMS? 

Thanks for your time in reading this issue - many thanks :)
