### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by handxr** [imranhsayed/nextjs-woocommerce-restapi#20]
I'm having this error while trying acces to the site , this is my general config
![e9fe7ae0fa4ca0defa0d83c8039f2445](https://user-images.githubusercontent.com/88827764/141700678-0a3f674a-3f24-4894-b646-e3b1ba6b38b0.png), if in the  site adress url is the top link there is no problem, the problem is when i am trying to acces from localhost:3000

**Comment by nagolicitest** [comment]
Hi did you find a fix for this?
