### ISSUE TITLE
When changing site address URL to local host and refreshing the JSON data previously fetched redirects to the localhost URL just set and returns a 404.

### ISSUE THREAD

**Issue by nagolicitest** [imranhsayed/nextjs-woocommerce-restapi#22]

**Comment by imranhsayed** [comment]
Can't replicate the issues..please record and share the recorded video link. Also add a screenshot of wp admin page where you have updated this url.

**Comment by Moe007** [comment]
Hi there,

I had the same/similar issue.

I changed the site url as follows:

![image](https://user-images.githubusercontent.com/26735673/149320226-c0733188-c243-4254-a09e-df92842c7ac0.png)

After doing that I was not able to access `wp-json`. Going to `http://localhost:81/wordpress/wp-json` would redirect to `http://localhost:3000/wordpress/wp-json` (My frontend) and results in a 404.

**To Fix This** I used `index.php` before `wp-json` like this `http://localhost:81/wordpress/index.php/wp-json` and it worked. 

I believe this is an issue with WordPress permalinks; see this post https://stackoverflow.com/questions/34670533/wordpress-rest-api-wp-api-404-error-cannot-access-the-wordpress-rest-api

**Comment by nagolicitest** [comment]
Thankyou for the response Moe and imran, i moved past the issue by using the rest api instead of graphQL - appreciate both of you responding will definitely be helpful in the future
