### ISSUE TITLE
No items added to cart

### ISSUE THREAD

**Issue by getakalabs-christarroja** [imranhsayed/nextjs-woocommerce-restapi#27]
After clicking "Add to Cart", the Bag (upper right) is not updated, and the cart is empty.

Steps I did to check if anything is working or not:

1 inspect page
- go to Network > two items/ show up
- first items/ (POST) show the correct Headers, Preview, and Response
- second items/ (GET) do not show anything in Preview and Response (only [])
- go to Application tab > my next-cart is 'null'

<img width="804" alt="Screen Shot 2022-04-28 at 5 18 22 PM" src="https://user-images.githubusercontent.com/48111294/165720672-7f9440ab-9427-45ee-8b9c-d3faffaa993f.png">

<img width="1063" alt="Screen Shot 2022-04-28 at 5 19 39 PM" src="https://user-images.githubusercontent.com/48111294/165720797-eda8a0b5-182c-4419-995c-5e4d5d3aa5d3.png">

2 But in Postman, everything works. (POST, GET, DELETE)

3 Double checked .env file and WooCommerce keys; I even "reinstalled" everything from the latest repo commit, npm install, etc... still the same result

**Comment by christarroja** [comment]
I was able to replicate the issue and solution. When returning to the same browser history (using old cookies/session), then I am not able to add to cart. Cart is not updating at all. 

But when I open localhost:3000 in a private/incognito window, then add to cart is now working. Deleting the browser cookies and site data for the site: localhost (127.0.0.1) will also solve this add to cart issue.

Not sure if this solves any problem, but hope you can comment about it.

**Comment by wchorski** [comment]
did you ever encounter this problem again? I seem to be running into the same problem on [My Issue](https://github.com/imranhsayed/nextjs-woocommerce-restapi/issues/33) 

it's as if axios.post is not feeding the data to the API, but in **POST MAN** post | get | delete works out as they should
