### ISSUE TITLE
Warning: Prop `dangerouslySetInnerHTML` did not match. From the footer

### ISSUE THREAD

**Issue by gmagnenat** [imranhsayed/nextjs-woocommerce-restapi#9]
Hello,

I have an issue with this warning coming from the footer component.
I compared with your code but I can't understand what I am missing here.
DOMPurify and the sanitize function seem to be correctly implemented.

Here is a link to my repo.
https://github.com/gmagnenat/nextjs-woocommerce-restapi

Thank you for your help

**Comment by imranhsayed** [comment]
Hi @gmagnenat ,
Thanks for writing,
The solution to the above problem is described here:
https://github.com/wwayne/react-tooltip/issues/675
https://stackoverflow.com/questions/64079321/react-tooltip-and-next-js-ssr-issue

I will send a PR soon.

**Comment by imranhsayed** [comment]
Done @gmagnenat 
https://github.com/imranhsayed/nextjs-woocommerce-restapi/pull/11
